#!/usr/bin/env python3
#
# pifon_audio_fake
#

import time
import random
import sys
import threading

def p(s):
  print("mon: "+s)
  sys.stdout.flush()

class Reader(threading.Thread):
  def run(self):
    while True:
      l = sys.stdin.readline()
      p("command:" + l)

r = Reader()
r.start()

rnd = random.randint
try:
  while True:
    w = rnd(0,5)
    time.sleep(w)
    p("audio_begin 127")
    for i in range(rnd(0,10)):
      time.sleep(0.5)
      p("audio_update %d" % rnd(0,128))
    p("audio_end 0")
except KeyboardInterrupt:
  pass
