#!/usr/bin/env python
#
# pifon_fon
#
# detect intervals ouf loudness and generate events
# uses SoX' rec tool with ALSA driver for USB WebCam audio
#

from __future__ import print_function

import os
import sys
import inspect

# add ../../tools to python path
my_dir = os.path.split(inspect.getfile( inspect.currentframe() ))[0]
tools_dir = os.path.realpath(os.path.abspath(os.path.join(my_dir,"..","..","tools")))
if tools_dir not in sys.path:
  sys.path.insert(0, tools_dir)

import bot
import audio

b = bot.Bot(True)
b.add_module(audio.AudioMod())
b.run()
