#!/usr/bin/env python
#
# pifon_mon
#
# controls the audio player
# shows audio events
#

from __future__ import print_function

import os
import sys
import inspect

# add ../../tools to python path
my_dir = os.path.split(inspect.getfile( inspect.currentframe() ))[0]
tools_dir = os.path.realpath(os.path.abspath(os.path.join(my_dir,"..","..","tools")))
if tools_dir not in sys.path:
  sys.path.insert(0, tools_dir)

import bot
import player
import ping
import info

b = bot.Bot(True)
b.add_module(player.PlayerMod())
b.add_module(ping.PingerMod())
b.add_module(info.InfoMod())
b.run()
