#!/bin/sh
#
# Usage: vumeter <SAMPLE_RATE> <INTERVAL> <CHANNELS>

SYSTEM=`uname -s`

if [ "$SYSTEM" = "Linux" ]; then
  # on linux use Alsa and "mixin" device
  export AUDIODRIVER=alsa
  export AUDIODEV=mixin
  RECORD="arecord -q -Dplug:pcm.mixin -f S16_LE"
else
  RECORD="rec -q -b 16 -t raw"
  POST_RECORD="- highpass 500"
fi

# default options
SAMPLE_RATE=22050
INTERVAL=100
CHANNELS=1

DIRNAME="`dirname \"$0\"`"

# optional give sample rate
if [ "$1" != "" ]; then
  SAMPLE_RATE=$1
fi
if [ "$2" != "" ]; then
  INTERVAL=$2
fi
if [ "$3" != "" ]; then
  CHANNELS=$3
fi

# run sox record and pipe to rms
exec ${RECORD} -c ${CHANNELS} -r ${SAMPLE_RATE} ${POST_RECORD} | \
  ${DIRNAME}/rms -c ${CHANNELS} -r ${SAMPLE_RATE} -i ${INTERVAL}
