#!/bin/sh
#
# Usage: vumeter <SAMPLE_RATE> <INTERVAL> <CHANNELS> <RECORDER> <DEVICE> <ZERO_RANGE>

SYSTEM=`uname -s`
DIRNAME="`dirname \"$0\"`"

# default options
if [ "$SAMPLE_RATE" = "" ]; then
  SAMPLE_RATE=48000
fi
if [ "$INTERVAL" = "" ]; then
  INTERVAL=250
fi
if [ "$CHANNELS" = "" ]; then
  CHANNELS=1
fi
if [ "$RECORDER" = "" ]; then
  RECORDER=rec
fi
if [ "$DEVICE" = "" ]; then
  DEVICE=mixin
fi
if [ "$ZERO_RANGE" = "" ]; then
  ZERO_RANGE=2000
fi

# optional give sample rate
if [ "$1" != "" ]; then
  SAMPLE_RATE=$1
fi
if [ "$2" != "" ]; then
  INTERVAL=$2
fi
if [ "$3" != "" ]; then
  CHANNELS=$3
fi
if [ "$4" != "" ]; then
  RECORDER=$4
fi
if [ "$5" != "" ]; then
  DEVICE=$5
fi
if [ "$6" != "" ]; then
  ZERO_RANGE=$6
fi

# show options
if [ "$DEBUG" != "" ]; then
  echo "SAMPLE_RATE=$SAMPLE_RATE INTERVAL=$INTERVAL CHANNELS=$CHANNELS RECORDER=$RECORDER DEVICE=$DEVICE ZERO_RANGE=$ZERO_RANGE" 2>&1
fi

if [ "$DEBUG" = "" ]; then
  QUIET="-q"
fi

# setup recorder
if [ "$RECORDER" = "arecord" ]; then
  # ALSA arecord
  RECORD="arecord $QUIET -D ${DEVICE} -f S16_LE -c ${CHANNELS} -r ${SAMPLE_RATE} highpass 500"
elif [ "$RECORDER" = "rec" ]; then
  # use sox' rec
  if [ "$SYSTEM" = "Linux" ]; then
    export AUDIODRIVER=alsa
    export AUDIODEV=${DEVICE}
  fi
  RECORD="rec $QUIET -b 16 -t raw -c ${CHANNELS} -r ${SAMPLE_RATE} -"
else
  echo "Unknown RECORDER=${RECORDER}!"
  exit 1
fi

# setup rms tools
EXTRA_RMS="-d -z $ZERO_RANGE"
if [ "$VERBOSE" != "" ]; then
  EXTRA_RMS="$EXTRA_RMS -v"
fi
RMS="${DIRNAME}/rms -c ${CHANNELS} -r ${SAMPLE_RATE} -i ${INTERVAL} ${EXTRA_RMS}"

# run sox record and pipe to rms
if [ "$DEBUG" != "" ]; then
  echo "$RECORD | $RMS"
fi
if [ "$DRYRUN" = "" ]; then
  exec ${RECORD} | ${RMS}
fi
