#!/bin/sh
# run a script as a given user in a tmux session:
#
# run_tmux <session> <action> <command>

SESSION_NAME="$1"
ACTION="$2"
COMMAND="$3"
if [ $# -lt 2 ]; then
  echo "Usage: $0 <session> <action> [command]"
  exit 1
fi

# make sure tmux is installed
TMUX=/usr/bin/tmux
if [ ! -x "$TMUX" ]; then
  echo "tmux not installed!"
  exit 4
fi

# action
case "$ACTION" in
  start)
    # start new tmux session
    echo "starting tmux session '$SESSION_NAME' command '$COMMAND'"
    $TMUX new-session -s $SESSION_NAME -d "$COMMAND"
    ;;
  status)    
    # check for tmux session and stop old one first
    $TMUX has-session -t $SESSION_NAME >/dev/null 2>&1
    if [ $? -eq 0 ]; then
      echo "tmux session '$SESSION_NAME' is running"
    else
      echo "tmux session '$SESSION_NAME' is NOT running"
    fi
    exit 0
    ;;
  stop)
    # send a Ctrl-C in session to stop it
    echo "stopping tmux session '$SESSION_NAME' command '$COMMAND'"
    $TMUX send-keys -t $SESSION_NAME C-c
    ;;
  *)
    echo "Unknown action: $ACTION"
    exit 1
esac
