#!/usr/bin/env python3
#
# pifon_client
#

import sys
import os
import subprocess

base_dir=os.path.dirname(sys.argv[0])

# main loop
try:
  while True:
    line = sys.stdin.readline().strip()
    # split command line
    args = line.split(',')
    if len(args) > 0:
      # extract command
      command = args[0]
      script_file = os.path.join(base_dir, command)
      # search for script
      if os.path.isfile(script_file):
        args[0] = script_file
        print("running:",args,file=sys.stderr)
        try:
          retcode = subprocess.call(args, shell=False)
          print("return:",retcode)
        except OSError as e:
          print("error:",e)
      else:
        print("unknown command:",script_file,file=sys.stderr)
    else:
      print("no command?",file=sys.stderr)
    sys.stderr.flush()
except KeyboardInterrupt:
  pass
